### ISSUE TITLE
Autoremove seems not be working

### ISSUE THREAD

**Issue by ClaudiuRoman** [cult-of-coders/grapher#146] opened 2017-06-13 09:01 UTC
Collection "ImageGroups" it's linked with collection Images, with the following properties:
```
images: {
        collection: Images,
        inversedBy: 'imageGroup',
        autoremove: true
    },
```
When I remove an imageGroup, I expect that all the image entries that has a link with imageGroup to be removed as well but it is not removing and I don't receive any errors / warnings

**Comment by theodorDiaconu** [comment] 2017-11-25 13:03
@ClaudiuRoman this works fine in a test. Cannot reproduce, I will close it for now, if you reproduce it, please show me link from Image Groups as well.

**Closed by theodorDiaconu** 2017-11-25 13:03 UTC
Labels: need-more-info
